server:
  port: 8080

spring:
  application:
    name: multi-datasource-with-transaction
#  profiles:
#    active: local

datasource:
  master:
    url: jdbc:mysql://localhost:3306/test_master
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    max-wait: 6000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  slave:
    url: jdbc:mysql://localhost:3306/test_slave
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    max-wait: 6000
    pool-prepared-statements: true
    max-open-prepared-statements: 20