server:
  port: 8080

spring:
  application:
    name: multi-datasource-with-transaction
#  profiles:
#    active: local

  datasource:
    master:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3306/test_second
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver